import Footer from "./components/shared/Footer/Footer";
import Navbar from "./components/shared/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "KeyCheck.ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>
        <main className="mt-16">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
